Repository KUIT-Space/KUIT-Space-front, pull requests merged in 2024-08, with the labels that each got.

#68 Feat#api - login api
  .eslintrc.cjs
  .eslintrc.json
  .gitignore
  .prettierignore
  mock/mockMSG.json
  mock/package-lock.json
  mock/package.json
  mock/server.js
  package.json
  src/App.tsx
  src/apis/LoginApi.ts
  src/apis/_createRequestOptions.ts
  src/apis/apis.ts
  src/apis/index.ts
  src/components/TopBarText.tsx
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ChatPage/ChatSettingPage/ChatSettingPage.tsx
  src/pages/ChatPage/ChattingPage/Chatting.css
  src/pages/ChatPage/ChattingPage/ChattingPage.styled.ts
  src/pages/ChatPage/ChattingPage/ChattingPage.tsx
  src/pages/ChatPage/_testChatList.ts
  src/pages/HomePage.tsx
  src/pages/LoginPage/LoginPage.tsx
  vite.config.ts
Labels: Feat

#92 Feat: Chat setting page
  src/App.tsx
  src/apis/Chat/ChatroomCreateApi.ts
  src/apis/Chat/ChatroomExitDelete.ts
  src/apis/Chat/ChatroomSearchAllUserApi.ts
  src/apis/Chat/ChatroomUpdateNameApi.ts
  src/apis/Chat/Socket.ts
  src/apis/LoginApi.ts
  src/apis/Space/SpaceSearchAllUserApi.ts
  src/apis/Space/SpaceSearchUserProfile.ts
  src/apis/Space/SpaceUserJoinApi.ts
  src/apis/_createRequestOptions.ts
  src/apis/index.ts
  src/assets/ChatPage/btn_add_member.svg
  src/components/BottomBtn.tsx
  src/components/TopBarText.tsx
  src/pages/ChatPage/ChatCreatePage/ChatCreatePage.styled.ts
  src/pages/ChatPage/ChatCreatePage/ChatCreatePage.tsx
  src/pages/ChatPage/ChatSettingPage/ChatSettingInvitePage.tsx
  src/pages/ChatPage/ChatSettingPage/ChatSettingMemberPage.tsx
  src/pages/ChatPage/ChatSettingPage/ChatSettingNamePage.tsx
  src/pages/ChatPage/ChatSettingPage/ChatSettingPage.tsx
  src/pages/ChatPage/ChattingPage/ChattingPage.styled.ts
  src/pages/ChatPage/ChattingPage/ChattingPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/SpacePage/InviteSpace.tsx
  src/pages/SpacePage/SpacePage.tsx
  src/utils/decodedJWT.ts
Labels: Feat

#98 Fix: signup user flow & verification logic
  src/App.tsx
  src/apis/Chat/Socket.ts
  src/apis/index.ts
  src/components/SignUpHeader.tsx
  src/pages/ChatPage/ChatPage.styled.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ChatPage/ChattingPage/ChattingPage.tsx
  src/pages/LoginPage/LoginModal.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/SignUpPage.styled.ts
  src/pages/LoginPage/SignUpPage.tsx
  src/utils/decodedJWT.ts
Labels: bug, Feat

#97 Feat/#85: 게시판 api 연동
  src/apis/Board/BoardPostApi.ts
  src/apis/Board/BoardPostDetailApi.ts
  src/apis/Board/BoardPostLikeApi.ts
  src/apis/Board/BoardReadApi.ts
  src/pages/BoardPage/BoardBottomModal.tsx
  src/pages/BoardPage/BoardDetailpage/BoardDetailPage.tsx
  src/pages/BoardPage/BoardPage.tsx
  src/pages/BoardPage/BoardPostItem.tsx
  src/pages/BoardPage/BoardRegisterPage/BoardRegisterPage.tsx
Labels: Feat, Style
